dataset:
  F_mult: 1
  T_mult: 1
dtc_decision_tree_classifier:
  architecture:
    criterion: gini
    max_depth: 5
    max_features: 14
    max_leaf_nodes: 15
    min_impurity_decrease: 0
    min_samples_leaf: 1
    min_samples_split: 2
features:
  abs_S_Smax: true
  abs_S_Smin: true
  abs_T_Tmax: true
  abs_T_Tmin: true
  count_anomalies_S: true
  count_anomalies_T: true
  max_variation_S: true
  max_variation_T: true
  mean_correlation: true
  nb_measurements: true
  ratio_anomalies_S: true
  ratio_anomalies_T: true
  rel_S_Smax_full_width: true
  rel_S_Smax_semi_width: true
  rel_S_Smin_full_width: true
  rel_S_Smin_semi_width: true
  rel_T_Tmax_full_width: true
  rel_T_Tmax_semi_width: true
  rel_T_Tmin_full_width: true
  rel_T_Tmin_semi_width: true
global_parameters:
  alarm_type: BOTH
  random_seed: 0
mlp_multi_layer_perceptron:
  batch_size: 16
  dropout: 0.5
  epochs: 250
  epsilon: 1.0e-08
  factor: 0.1
  growth_rate: 16
  learning_rate: 0.01
  patience: 10
rfc_random_forest_classifier:
  architecture:
    criterion: gini
    max_depth: 5
    max_features: 14
    max_leaf_nodes: 15
    min_impurity_decrease: 0
    min_samples_leaf: 1
    min_samples_split: 2
    number_of_trees: 11
